enum Asset {
    static let scheduleIcon = "ScheduleIcon"
    static let scheduleIconSelected = "ScheduleIconSelected"
    static let profileIcon = "ProfileIcon"
    static let profileIconSelected = "ProfileIconSelected"
    static let verticaldots = "verticaldots"
    static let bookIcon = "BookIcon"
    static let bookIconSelected = "BookIconSelected"
    static let lineChartIcon = "LineChartIcon"
    static let lineChartIconSelected = "LineChartIconSelected"
    static let globe = "Globe"
    static let regularchevronRight = "regularchevron-right"
    static let regularchevronLeft = "regularchevron-left"
    static let notepad = "Notepad"
    static let greenQuestionMark = "GreenQuestionMark"
    static let thumbUp = "ThumbUp"
    static let lock = "lock"
    static let logout = "logout"
    static let regularedit = "regularedit"
    static let calendarIcon = "CalendarIcon"
    static let bell = "bell"
    static let eyeIcon = "EyeIcon"
    static let eyeSlashIcon = "EyeSlashIcon"
}
